services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: licitaciones_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - initdb database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: licitaciones_db

volumes:
  postgres_data:
